/*
 * This file is generated by jOOQ.
 */
package net.toadless.permissionsplus.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String uuid;
    private final Long   groupId;

    public Users(Users value) {
        this.uuid = value.uuid;
        this.groupId = value.groupId;
    }

    public Users(
        String uuid,
        Long   groupId
    ) {
        this.uuid = uuid;
        this.groupId = groupId;
    }

    /**
     * Getter for <code>public.users.uuid</code>.
     */
    public String getUuid() {
        return this.uuid;
    }

    /**
     * Getter for <code>public.users.group_id</code>.
     */
    public Long getGroupId() {
        return this.groupId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(uuid);
        sb.append(", ").append(groupId);

        sb.append(")");
        return sb.toString();
    }
}
